version: "3.8"

services:
  gokite-nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    image: gokite-nextjs:latest
    container_name: gokite-nextjs-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=https://gokite-sit-b2c.convergentechnologies.com
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:3000",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
