apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gokite

resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  # - ingress.yaml  # Uncomment when ready to use

commonLabels:
  app: gokite-nextjs
  version: v1.0.0
  managed-by: kustomize
